---
AWSTemplateFormatVersion: 2010-09-09


Description: >
  This template contains the services required to run lighthouse ci server


Parameters:
  TemplateBucket:
    Type: String
    Default: tp-todo-react-testing-infrastructure
    Description: >
      The S3 bucket from which to fetch the templates used by this stack.

  DNSName:
    Type: String

  Cluster:
    Type: String

  DesiredCount:
    Type: Number
    Default: 0
  
  ImageURI:
    Type: String

  SourceSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id

  VpcId:
    Type: AWS::EC2::VPC::Id

  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
  
  ParentListenerARN:
    Type: String

  Env:
    Type: String
    AllowedValues:
      - production
      - staging


Mappings:
  ENVLBPriority:
    production:
      Main: 7
    staging:
      Main: 8

Resources:
  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub ${AWS::StackName}-secgroup-lighthouse
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 9001
          ToPort: 9001
          SourceSecurityGroupId: !Ref SourceSecurityGroup

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${AWS::StackName}-lighthouse

  FargateService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref TaskDefinition
      LaunchType: FARGATE
      SchedulingStrategy: REPLICA
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 75
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref ContainerSecurityGroup
          Subnets: !Ref Subnets
      LoadBalancers:
        - ContainerName: lighthouse
          ContainerPort: 9001
          TargetGroupArn: !Ref TargetGroup

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${AWS::StackName}-lighthouse
      RequiresCompatibilities:
        - FARGATE
      Memory: 512
      Cpu: 256
      NetworkMode: awsvpc
      ExecutionRoleArn: !Ref TaskExecutionRole
      ContainerDefinitions:
        - Name: lighthouse
          Image: !Ref ImageURI
          Essential: true
          PortMappings:
            - ContainerPort: 9001
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: !Sub ${AWS::StackName}-lighthouse
          MountPoints:
            - ContainerPath: /data
              SourceVolume: lighthouse_data
      Volumes:
        - Name: lighthouse_data


  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: 9001
      Protocol: HTTP
      Matcher:
        HttpCode: 200-302
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      TargetType: "ip"
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 30

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref ParentListenerARN
      Priority: !FindInMap [ENVLBPriority, !Ref Env, Main]
      Conditions:
        - Field: host-header
          Values:
            - !Ref DNSName
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward

Outputs:
  Service:
    Value: !Ref FargateService

  ServiceLink:
    Value: !Sub https://${DNSName}/
